Fix linux16 -> initrd16 in 10_linux
Using linux16 for an initramfs.img causes the boot to fail with
  error: invalid magic number.

This seems to have been accidentally introduced in commit 752ceb1640e8
(2.02-38) while rebasing the patches to fedora-29.

Tested: Regenerated Grub config with grub2-mkconfig, confirmed that
initrd16 was used by inspecting grub.cfg, successfully rebooted the
system.